# Regenerated by `mix spark.formatter` from the DSL extensions — do not hand-edit.
spark_locals_without_parens = [
  action: 1,
  activate_action: 1,
  attribute: 1,
  created_at: 1,
  created_by: 1,
  deactivate_action: 1,
  description: 1,
  enabled?: 1,
  entry: 1,
  entry: 2,
  exclude_actions: 1,
  group: 2,
  group: 3,
  icon: 1,
  label: 1,
  on: 1,
  prefix: 1,
  reason: 1,
  record_sensitive: 1,
  restrict: 2,
  restrict: 3,
  search_argument: 1,
  store: 1,
  updated_at: 1,
  updated_by: 1
]

# Non-Spark locals (the router macro) — kept separate so `mix spark.formatter`
# regeneration of the list above doesn't drop them.
extra_locals_without_parens = [
  quick_view: 2,
  quick_view: 3
]

locals_without_parens = spark_locals_without_parens ++ extra_locals_without_parens

[
  import_deps: [:ash, :ash_phoenix, :spark, :phoenix, :phoenix_live_view],
  inputs: ["*.{ex,exs}", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter, Phoenix.LiveView.HTMLFormatter],
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
