defmodule ExampleWeb.BulkActionScenarioTest do
  @moduledoc """
  Running one action over a selection of rows.

  Two kinds of action end up in the same menu, and the difference matters. The
  **derived** ones are every input-less update and every destroy the actor may
  run, taken off the resource — `ExampleWeb.ProductLive.Quick` names none of
  them. The **declared** ones come from `list: [bulk_actions: ...]`, for the
  operations that cannot be derived because they need a value nobody has been
  asked for.

  The menu is also the clearest case of a control that is not there for two
  different reasons: nothing is selected, or the actor may not run it. Both are
  driven, because a `refute_has` that passes for the first reason would pass for
  the second whether or not the permission works.
  """
  use ExampleWeb.FeatureCase, async: true

  # The row actions share the menu's labels, so a bulk one is addressed by the
  # event it pushes rather than by its text.
  @bulk "a[phx-click*='bulk_action']"

  setup %{admin: admin} do
    %{
      first: product(name: "First tent", price: Money.new(:USD, "100.00"), actor: admin),
      second: product(name: "Second tent", price: Money.new(:USD, "50.00"), actor: admin),
      untouched: product(name: "Untouched tent", price: Money.new(:USD, "20.00"), actor: admin)
    }
  end

  describe "the menu" do
    test "appears only once something is selected", ctx do
      %{conn: conn, admin: admin, first: first} = ctx

      conn
      |> log_in(admin)
      |> visit(~p"/products")
      # Nothing ticked: there is no selection to act on, so there is no menu.
      |> refute_has(@bulk)
      |> tick_rows([first.id])
      |> assert_has(@bulk, text: "Deactivate")
    end

    test "offers what the resource has, without the page naming any of it", ctx do
      %{conn: conn, admin: admin, first: first} = ctx

      session =
        conn
        |> log_in(admin)
        |> visit(~p"/products")
        |> tick_rows([first.id])

      # `:activate` / `:deactivate` are generated by the activation declaration,
      # `:destroy` is a default. All three take no input, so they can be run
      # over a selection without asking anything.
      session
      |> assert_has(@bulk, text: "Deactivate")
      |> assert_has(@bulk, text: "Activate")
      |> assert_has(@bulk, text: "Delete")
      # `:reprice` takes a price, so it is *not* derivable — the declared
      # action below is what supplies one.
      |> refute_has(@bulk, text: "Reprice")
      |> assert_has("a", text: "Discount 10%")
    end

    test "a role the policy refuses is offered nothing over a selection", ctx do
      %{conn: conn, viewer: viewer, editor: editor, first: first} = ctx

      # A viewer writes nothing at all, so the menu has no contents and does not
      # render even with a row ticked.
      conn
      |> log_in(viewer)
      |> visit(~p"/products")
      |> tick_rows([first.id])
      |> refute_has(@bulk)
      |> refute_has("a", text: "Discount 10%")

      # An editor is the sharper case: they may deactivate, so the menu *is*
      # there — and the one action they may not run is the one missing from it.
      conn
      |> log_in(editor)
      |> visit(~p"/products")
      |> tick_rows([first.id])
      |> assert_has(@bulk, text: "Deactivate")
      |> refute_has("a", text: "Discount 10%")
    end
  end

  describe "running one" do
    test "a derived action changes every selected row and nothing else", ctx do
      %{conn: conn, admin: admin, first: first, second: second, untouched: untouched} = ctx

      conn
      |> log_in(admin)
      |> visit(~p"/products")
      |> tick_rows([first.id, second.id])
      |> click_link(@bulk, "Deactivate")
      # The list re-reads itself, so the two rows are dimmed without a reload.
      |> assert_has("tr[id='#{first.id}'].opacity-50")
      |> assert_has("tr[id='#{second.id}'].opacity-50")
      |> refute_has("tr[id='#{untouched.id}'].opacity-50")

      refute Ash.reload!(first, authorize?: false).active
      refute Ash.reload!(second, authorize?: false).active
      assert Ash.reload!(untouched, authorize?: false).active
    end

    test "a declared action runs the one the resource could not offer", ctx do
      %{conn: conn, admin: admin, first: first, second: second, untouched: untouched} = ctx

      conn
      |> log_in(admin)
      |> visit(~p"/products")
      |> tick_rows([first.id, second.id])
      |> click_link("a", "Discount 10%")
      |> assert_has("*", text: "Repriced 2 products.")

      assert Money.to_string!(Ash.reload!(first, authorize?: false).price) =~ "90"
      assert Money.to_string!(Ash.reload!(second, authorize?: false).price) =~ "45"
      assert Money.to_string!(Ash.reload!(untouched, authorize?: false).price) =~ "20"

      # It ran the real action, so the trail and the price-change log both have
      # it — which is the reason to reach for an action rather than a write.
      assert repriced_ids() == MapSet.new([first.id, second.id])
    end

    test "the selection is cleared afterwards, so it cannot be run twice by accident", ctx do
      %{conn: conn, admin: admin, first: first} = ctx

      conn
      |> log_in(admin)
      |> visit(~p"/products")
      |> tick_rows([first.id])
      |> click_link("a", "Discount 10%")
      |> refute_has(@bulk)

      assert Money.to_string!(Ash.reload!(first, authorize?: false).price) =~ "90"
    end

    # A bulk action is a write per row rather than one transaction, so a refusal
    # partway through does not undo the rows that already went through. Stopping
    # at it only loses the fact that they did — which is the state an operator
    # then has to guess at.
    test "a row the lock refuses does not stop the rows it does not", ctx do
      %{conn: conn, admin: admin, first: first, second: second} = ctx

      session =
        conn
        |> log_in(admin)
        |> visit(~p"/products")
        |> tick_rows([first.id, second.id])

      # The page is holding both rows as they were at version 1. Moving one of
      # them out from under it is what the optimistic lock refuses, and it
      # refuses exactly one of the two rows the click is about to reprice.
      Ash.update!(second, %{description: "moved by somebody else"},
        actor: admin,
        authorize?: false
      )

      session
      |> click_link("a", "Discount 10%")
      |> assert_has("*", text: "Repriced 1 of 2 products.")
      |> assert_has("*", text: AshQuick.LiveView.ActionErrors.stale_message())

      # The row the lock let through is repriced, and said to be.
      assert Money.to_string!(Ash.reload!(first, authorize?: false).price) =~ "90"
      assert Money.to_string!(Ash.reload!(second, authorize?: false).price) =~ "50"
    end

    test "a second run does not discount a row the first one already did", ctx do
      %{conn: conn, admin: admin, first: first, second: second} = ctx

      session =
        conn
        |> log_in(admin)
        |> visit(~p"/products")
        |> tick_rows([first.id, second.id])

      Ash.update!(second, %{description: "moved by somebody else"},
        actor: admin,
        authorize?: false
      )

      # The selection that survives a partial run is the rows that did *not* go
      # through, so running it again is a retry rather than a second discount.
      # Keeping the whole selection would compound 10% onto the rows that
      # already took it — and the operator retrying a run that reported an
      # error has every reason to.
      session
      |> click_link("a", "Discount 10%")
      |> click_link("a", "Discount 10%")

      assert Money.to_string!(Ash.reload!(first, authorize?: false).price) =~ "90"
      refute Money.to_string!(Ash.reload!(first, authorize?: false).price) =~ "81"
    end

    test "an event forged without the button is refused by the policy behind it", ctx do
      %{conn: conn, editor: editor, first: first} = ctx

      # The editor has no "Discount 10%" link. Pushing the event anyway is what
      # somebody editing the DOM would do, and `:reprice`'s policy — not the
      # missing control — is what stops it.
      session =
        conn
        |> log_in(editor)
        |> visit(~p"/products")
        |> tick_rows([first.id])
        |> refute_has("a", text: "Discount 10%")

      PhoenixTest.unwrap(session, fn view -> render_click(view, "discount", %{}) end)

      session
      |> assert_has("*", text: AshQuick.LiveView.ActionErrors.forbidden_message())

      assert Money.to_string!(Ash.reload!(first, authorize?: false).price) =~ "100"
    end
  end

  # Ticking a row is a change on the list's own form, which is what the
  # checkboxes live in.
  defp tick_rows(session, ids) do
    params = Map.new(ids, &{&1, "on"})

    PhoenixTest.unwrap(session, fn view ->
      render_change(view, "table-form-change", params)
    end)
  end

  defp repriced_ids do
    Example.Catalog.PriceChange
    |> Ash.read!(authorize?: false)
    |> MapSet.new(& &1.product_id)
  end
end
