defmodule Example.Test.S3Stub do
  @moduledoc """
  A bucket that lives in ETS, so an export can be driven end to end offline.

  Everything else about the storage seam is offline already — a presigned URL is
  a signature computed locally, which is why `Example.Test.PresignHelpers` can
  assert on one without a network. `AshQuick.LiveView.ExportUtils` is the
  exception: it writes the generated file through `AshQuick.Storage.upload/3`,
  which is a real multipart `PUT`. Without something here the export can only be
  tested as far as the button.

  So this stands in for S3 at the HTTP layer rather than replacing the storage
  module: the CSV is really generated by `NimbleCSV`, the workbook really by
  `Exceed`, the key really built by `ExportUtils`, and the bytes that arrive are
  the bytes a reader would have downloaded. `body/1` hands them back.

  One row per part — keyed `{key, part_number}` rather than a parts list under
  the key — so an upload is a sequence of independent `insert`s. A list would
  have to be read, prepended to and written back, and two parts doing that at
  once lose one of themselves; `ExAws.S3.upload/4` is free to send parts
  concurrently, and does once a file is larger than one chunk.
  """

  @behaviour ExAws.Request.HttpClient

  @table __MODULE__

  @doc "Starts the table. Called once from `test_helper.exs`."
  def start do
    :ets.new(@table, [:named_table, :public, :set, write_concurrency: true])
    :ok
  end

  @doc """
  The bytes uploaded to `key`, or `nil` if nothing was.

  Parts are concatenated in order, which is what the object would be.
  """
  def body(key) do
    case parts(key) do
      [] -> nil
      parts -> parts |> Enum.sort_by(&elem(&1, 0)) |> Enum.map_join("", &elem(&1, 1))
    end
  end

  @doc """
  Every key written so far.

  Here rather than in the tests, so how a part is stored stays this module's
  business.
  """
  def keys do
    @table |> :ets.match({{:"$1", :_}, :_}) |> List.flatten() |> Enum.uniq()
  end

  @doc "Forgets everything, for a test that wants to assert nothing was written."
  def clear, do: :ets.delete_all_objects(@table)

  defp parts(key) do
    @table
    |> :ets.match({{key, :"$1"}, :"$2"})
    |> Enum.map(fn [number, body] -> {number, body} end)
  end

  @impl true
  def request(method, url, body, _headers, _http_opts) do
    uri = URI.parse(url)
    query = URI.decode_query(uri.query || "")
    key = uri.path |> String.trim_leading("/") |> URI.decode()

    respond(method, key, query, body)
  end

  # Initiate. The upload id is the key, since nothing here multiplexes.
  defp respond(:post, key, %{"uploads" => _}, _body) do
    xml("""
    <InitiateMultipartUploadResult>
      <UploadId>#{key}</UploadId>
    </InitiateMultipartUploadResult>
    """)
  end

  # Complete. The parts are already in the table.
  defp respond(:post, _key, %{"uploadId" => _}, _body) do
    xml("""
    <CompleteMultipartUploadResult>
      <ETag>"complete"</ETag>
    </CompleteMultipartUploadResult>
    """)
  end

  # One part of the object. `ExAws.S3.Upload` needs the `ETag` header back to
  # name it in the completion request.
  defp respond(:put, key, %{"partNumber" => number}, body) do
    :ets.insert(@table, {{key, String.to_integer(number)}, body})

    {:ok, %{status_code: 200, headers: [{"ETag", ~s("#{number}")}], body: ""}}
  end

  # A single-shot `PUT`, for anything that does not go through the multipart
  # path.
  defp respond(:put, key, _query, body) do
    :ets.match_delete(@table, {{key, :_}, :_})
    :ets.insert(@table, {{key, 1}, body})
    {:ok, %{status_code: 200, headers: [{"ETag", ~s("1")}], body: ""}}
  end

  defp respond(_method, _key, _query, _body) do
    {:ok, %{status_code: 200, headers: [], body: ""}}
  end

  defp xml(body), do: {:ok, %{status_code: 200, headers: [], body: body}}
end
