defmodule Example.Repo.Migrations.SkuUniqueWithoutAStore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:products, [:store_id, :sku], name: "products_sku_index")

    create unique_index(:products, [:store_id, :sku],
             name: "products_sku_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:products, [:store_id, :sku], name: "products_sku_index")

    create unique_index(:products, [:store_id, :sku], name: "products_sku_index")
  end
end
