defmodule Example.Repo.Migrations.ActorInsertedBy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:brands, "brands_created_by_id_fkey")

    rename table(:brands), :created_by_id, to: :inserted_by_id

    alter table(:brands) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "brands_inserted_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    drop constraint(:categories, "categories_created_by_id_fkey")

    rename table(:categories), :created_by_id, to: :inserted_by_id

    alter table(:categories) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "categories_inserted_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    drop constraint(:price_changes, "price_changes_created_by_id_fkey")

    rename table(:price_changes), :created_by_id, to: :inserted_by_id

    alter table(:price_changes) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "price_changes_inserted_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    drop constraint(:products, "products_created_by_id_fkey")

    rename table(:products), :created_by_id, to: :inserted_by_id

    alter table(:products) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "products_inserted_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    drop constraint(:stores, "stores_created_by_id_fkey")

    rename table(:stores), :created_by_id, to: :inserted_by_id

    alter table(:stores) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "stores_inserted_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end
  end

  def down do
    drop constraint(:stores, "stores_inserted_by_id_fkey")

    alter table(:stores) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "stores_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    rename table(:stores), :inserted_by_id, to: :created_by_id

    drop constraint(:products, "products_inserted_by_id_fkey")

    alter table(:products) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "products_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    rename table(:products), :inserted_by_id, to: :created_by_id

    drop constraint(:price_changes, "price_changes_inserted_by_id_fkey")

    alter table(:price_changes) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "price_changes_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    rename table(:price_changes), :inserted_by_id, to: :created_by_id

    drop constraint(:categories, "categories_inserted_by_id_fkey")

    alter table(:categories) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "categories_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    rename table(:categories), :inserted_by_id, to: :created_by_id

    drop constraint(:brands, "brands_inserted_by_id_fkey")

    alter table(:brands) do
      modify :inserted_by_id,
             references(:users,
               column: :id,
               name: "brands_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    rename table(:brands), :inserted_by_id, to: :created_by_id
  end
end
