defmodule Example.Repo.Migrations.FileObjectReferencedBy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file_objects) do
      add :referenced_by_id,
          references(:users,
            column: :id,
            name: "file_objects_referenced_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:file_objects, "file_objects_referenced_by_id_fkey")

    alter table(:file_objects) do
      remove :referenced_by_id
    end
  end
end
