defmodule Example.Repo.Migrations.AddStores do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:price_changes, "price_changes_product_id_fkey")

    alter table(:price_changes) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "price_changes_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :restrict
             )
    end

    drop_if_exists unique_index(:products, [:sku], name: "products_sku_index")

    alter table(:products) do
      add :store_id, :uuid
    end

    create unique_index(:products, [:store_id, :sku], name: "products_sku_index")

    create table(:stores, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:products) do
      modify :store_id,
             references(:stores,
               column: :id,
               name: "products_store_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:stores) do
      add :code, :text, null: false
      add :name, :text, null: false
      add :active, :boolean, default: true
      add :version, :bigint, null: false, default: 1

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "stores_created_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          ), null: false
    end

    create unique_index(:stores, [:code], name: "stores_code_index")

    alter table(:stores) do
      add :updated_by_id,
          references(:users,
            column: :id,
            name: "stores_updated_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          ), null: false
    end

    alter table(:users) do
      add :store_id,
          references(:stores,
            column: :id,
            name: "users_store_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:users, "users_store_id_fkey")

    alter table(:users) do
      remove :store_id
    end

    drop constraint(:stores, "stores_updated_by_id_fkey")

    drop constraint(:stores, "stores_created_by_id_fkey")

    alter table(:stores) do
      remove :updated_by_id
    end

    drop_if_exists unique_index(:stores, [:code], name: "stores_code_index")

    alter table(:stores) do
      remove :created_by_id
      remove :updated_at
      remove :created_at
      remove :version
      remove :active
      remove :name
      remove :code
    end

    drop constraint(:products, "products_store_id_fkey")

    alter table(:products) do
      modify :store_id, :uuid
    end

    drop table(:stores)

    drop_if_exists unique_index(:products, [:store_id, :sku], name: "products_sku_index")

    alter table(:products) do
      remove :store_id
    end

    create unique_index(:products, [:sku], name: "products_sku_index")

    drop constraint(:price_changes, "price_changes_product_id_fkey")

    alter table(:price_changes) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "price_changes_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :restrict
             )
    end
  end
end
