defmodule Example.Repo.Migrations.ActivationNotNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brands) do
      modify :active, :boolean, null: false
    end

    alter table(:categories) do
      modify :active, :boolean, null: false
    end

    alter table(:products) do
      modify :active, :boolean, null: false
    end

    alter table(:stores) do
      modify :active, :boolean, null: false
    end

    alter table(:users) do
      modify :active, :boolean, null: false
    end
  end

  def down do
    alter table(:users) do
      modify :active, :boolean, null: true
    end

    alter table(:stores) do
      modify :active, :boolean, null: true
    end

    alter table(:products) do
      modify :active, :boolean, null: true
    end

    alter table(:categories) do
      modify :active, :boolean, null: true
    end

    alter table(:brands) do
      modify :active, :boolean, null: true
    end
  end
end
