defmodule Example.Repo.Migrations.AddAuditLogChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_logs) do
      add :changes, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:audit_logs) do
      remove :changes
    end
  end
end
