defmodule Example.Repo.Migrations.AddCategoryDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add :documents, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:categories) do
      remove :documents
    end
  end
end
