defmodule Example.Repo.Migrations.TimestampsInsertedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:audit_logs), :created_at, to: :inserted_at

    rename table(:brands), :created_at, to: :inserted_at

    rename table(:categories), :created_at, to: :inserted_at

    rename table(:file_objects), :created_at, to: :inserted_at

    rename table(:price_changes), :created_at, to: :inserted_at

    rename table(:products), :created_at, to: :inserted_at

    rename table(:stores), :created_at, to: :inserted_at

    rename table(:users), :created_at, to: :inserted_at
  end

  def down do
    rename table(:users), :inserted_at, to: :created_at

    rename table(:stores), :inserted_at, to: :created_at

    rename table(:products), :inserted_at, to: :created_at

    rename table(:price_changes), :inserted_at, to: :created_at

    rename table(:file_objects), :inserted_at, to: :created_at

    rename table(:categories), :inserted_at, to: :created_at

    rename table(:brands), :inserted_at, to: :created_at

    rename table(:audit_logs), :inserted_at, to: :created_at
  end
end
