defmodule Example.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :resource_name, :text, null: false
      add :resource_id, :uuid, null: false
      add :action_type, :text, null: false
      add :action_name, :text, null: false
      add :attributes, :map, null: false
      add :arguments, :map, null: false
      add :context, :map, null: false
      add :ip, :text
      add :tenant, :uuid

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id, :uuid
      add :real_actor_id, :uuid
    end

    create index(:audit_logs, [:resource_id, :resource_name])

    create index(:audit_logs, [:actor_id])

    create table(:brands, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :code, :text, null: false
      add :name, :text, null: false
      add :active, :boolean, default: true
      add :version, :bigint, null: false, default: 1

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id, :uuid, null: false
    end

    create unique_index(:brands, [:code], name: "brands_code_index")

    alter table(:brands) do
      add :updated_by_id, :uuid, null: false
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :code, :text, null: false
      add :name, :text, null: false
      add :image, :map
      add :active, :boolean, default: true
      add :version, :bigint, null: false, default: 1

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          )
    end

    create unique_index(:categories, [:code], name: "categories_code_index")

    alter table(:categories) do
      add :created_by_id, :uuid, null: false
      add :updated_by_id, :uuid, null: false
    end

    create table(:file_objects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false
      add :state, :text, null: false, default: "processing"
      add :source, :text, null: false
      add :accepts, {:array, :text}
      add :max_bytes, :bigint
      add :content_type, :text
      add :byte_size, :bigint
      add :original_filename, :text
      add :resource_name, :text
      add :resource_id, :uuid
      add :referenced_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id, :uuid
    end

    create unique_index(:file_objects, [:key], name: "file_objects_unique_key_index")

    create index(:file_objects, [:state])

    create index(:file_objects, [:referenced_at])

    create table(:price_changes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :from_price, :money_with_currency
      add :to_price, :money_with_currency, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id, :uuid, null: false
      add :created_by_id, :uuid, null: false
    end

    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:price_changes) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "price_changes_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :restrict
             )
    end

    alter table(:products) do
      add :sku, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :price, :money_with_currency, null: false
      add :tags, {:array, :text}, default: []
      add :images, {:array, :map}, default: []
      add :active, :boolean, default: true
      add :version, :bigint, null: false, default: 1

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brand_id,
          references(:brands,
            column: :id,
            name: "products_brand_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          ),
          null: false
    end

    create unique_index(:products, [:sku], name: "products_sku_index")

    alter table(:products) do
      add :category_id,
          references(:categories,
            column: :id,
            name: "products_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          ),
          null: false

      add :created_by_id, :uuid, null: false
      add :updated_by_id, :uuid, null: false
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:audit_logs) do
      modify :actor_id,
             references(:users,
               column: :id,
               name: "audit_logs_actor_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )

      modify :real_actor_id,
             references(:users,
               column: :id,
               name: "audit_logs_real_actor_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:brands) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "brands_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )

      modify :updated_by_id,
             references(:users,
               column: :id,
               name: "brands_updated_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:categories) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "categories_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )

      modify :updated_by_id,
             references(:users,
               column: :id,
               name: "categories_updated_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:file_objects) do
      modify :actor_id,
             references(:users,
               column: :id,
               name: "file_objects_actor_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    alter table(:price_changes) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "price_changes_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:products) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "products_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )

      modify :updated_by_id,
             references(:users,
               column: :id,
               name: "products_updated_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:users) do
      add :name, :text, null: false
      add :email, :citext, null: false
      add :role, :text, null: false, default: "viewer"
      add :active, :boolean, default: true
      add :version, :bigint, null: false, default: 1

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_email_index")

    alter table(:users) do
      remove :updated_at
      remove :created_at
      remove :version
      remove :active
      remove :role
      remove :email
      remove :name
    end

    drop constraint(:products, "products_updated_by_id_fkey")

    drop constraint(:products, "products_created_by_id_fkey")

    drop constraint(:products, "products_category_id_fkey")

    drop constraint(:products, "products_brand_id_fkey")

    alter table(:products) do
      modify :updated_by_id, :uuid
      modify :created_by_id, :uuid
    end

    drop constraint(:price_changes, "price_changes_created_by_id_fkey")

    drop constraint(:price_changes, "price_changes_product_id_fkey")

    alter table(:price_changes) do
      modify :created_by_id, :uuid
    end

    drop constraint(:file_objects, "file_objects_actor_id_fkey")

    alter table(:file_objects) do
      modify :actor_id, :uuid
    end

    drop constraint(:categories, "categories_updated_by_id_fkey")

    drop constraint(:categories, "categories_created_by_id_fkey")

    drop constraint(:categories, "categories_parent_id_fkey")

    alter table(:categories) do
      modify :updated_by_id, :uuid
      modify :created_by_id, :uuid
    end

    drop constraint(:brands, "brands_updated_by_id_fkey")

    drop constraint(:brands, "brands_created_by_id_fkey")

    alter table(:brands) do
      modify :updated_by_id, :uuid
      modify :created_by_id, :uuid
    end

    drop constraint(:audit_logs, "audit_logs_real_actor_id_fkey")

    drop constraint(:audit_logs, "audit_logs_actor_id_fkey")

    alter table(:audit_logs) do
      modify :real_actor_id, :uuid
      modify :actor_id, :uuid
    end

    drop table(:users)

    alter table(:products) do
      remove :updated_by_id
      remove :created_by_id
      remove :category_id
    end

    drop_if_exists unique_index(:products, [:sku], name: "products_sku_index")

    alter table(:products) do
      remove :brand_id
      remove :updated_at
      remove :created_at
      remove :version
      remove :active
      remove :images
      remove :tags
      remove :price
      remove :description
      remove :name
      remove :sku
    end

    alter table(:price_changes) do
      modify :product_id, :uuid
    end

    drop table(:products)

    drop table(:price_changes)

    drop_if_exists index(:file_objects, [:referenced_at])

    drop_if_exists index(:file_objects, [:state])

    drop_if_exists unique_index(:file_objects, [:key], name: "file_objects_unique_key_index")

    drop table(:file_objects)

    alter table(:categories) do
      remove :updated_by_id
      remove :created_by_id
    end

    drop_if_exists unique_index(:categories, [:code], name: "categories_code_index")

    drop table(:categories)

    alter table(:brands) do
      remove :updated_by_id
    end

    drop_if_exists unique_index(:brands, [:code], name: "brands_code_index")

    drop table(:brands)

    drop_if_exists index(:audit_logs, [:actor_id])

    drop_if_exists index(:audit_logs, [:resource_id, :resource_name])

    drop table(:audit_logs)
  end
end
